name: ContanarizedBuildACR

on: workflow_dispatch

permissions:                # OpenID Connect (OIDC) authentication. requireds read write permission:
  id-token: write           # other wise gives error: Failed to fetch federated token from GitHub. Please make sure to give write permissions to id-token in the workflow
  contents: read

jobs:
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4         

    # Login to Azure using OIDC or a Service Principal
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure ACR login
      run: az acr login --name acrazuresantosh   #  ACR name

    - name: Docker Build 
      run: |
        docker build -t python-sum:pythonimage .    
        
    - name: Tag image for ACR
      run: |
        docker tag python-sum:pythonimage \
          acrazuresantosh.azurecr.io/git-action-images:pythonimage
          
    - name: Push to Azure Container Registry
      run: |
        docker push acrazuresantosh.azurecr.io/git-action-images:pythonimage     #  ACR login server ( private registry endpoint).
